spring.application.name=PULSEHR
spring.profiles.active=dev

spring.datasource.url=postgresql://pulsehr_bbjj_user:NFD4wQiTdwR4IDAysLFJ2vocGFfcokzV@dpg-dabb4bn10e5c73adqq5g-a/pulsehr_bbjj
spring.datasource.username=pulsehr_bbjj_user
spring.datasource.password=NFD4wQiTdwR4IDAysLFJ2vocGFfcokzV
spring.datasource.driver-class-name=org.postgresql.Driver

# Optionnel : désactive la détection H2 par défaut si présente
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JPA / Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
