server.port=8080
spring.datasource.url=jdbc:h2:mem:pulsehrdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false

# Frequence des cron en Dev (Toutes les 2 minutes pour tester)
pulsehr.cron.verification-contrats=0 */2 * * * *
pulsehr.cron.rapport-periodic=0 */2 * * * *
pulsehr.cron.nettoyage-evaluations=0 */2 * * * *