server.port=8080

spring.h2.console.enabled=true

spring.datasource.url=jdbc:postgresql://pulsehr_bbjj_user:NFD4wQiTdwR4IDAysLFJ2vocGFfcokzV@dpg-dabb4bn10e5c73adqq5g-a/pulsehr_bbjj
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=pulsehr_bbjj_user
spring.datasource.password=NFD4wQiTdwR4IDAysLFJ2vocGFfcokzV

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false

# Frequence des cron en Dev (Toutes les 2 minutes pour tester)
pulsehr.cron.verification-contrats=0 */2 * * * *
pulsehr.cron.rapport-periodic=0 */2 * * * *
pulsehr.cron.nettoyage-evaluations=0 */2 * * * *