server.port=80
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.thymeleaf.cache=true

# Frequences standards Prod
pulsehr.cron.verification-contrats=0 0 0 * * *
pulsehr.cron.rapport-periodic=0 0 * * * *
pulsehr.cron.nettoyage-evaluations=0 0 3 * * SUN